spring.application.name=fincoach-ai

# PostgreSQL
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5434/fincoach_db
spring.datasource.username=postgres
spring.datasource.password=@Selflove01
spring.jpa.hibernate.ddl-auto=update  # Automatically update schema
spring.jpa.show-sql=true               # Log SQL queries for debugging

# JWT (add later when implementing security)
jwt.secret=yourSecretKeyHere
jwt.expiration=86400000

# Spring Doc OpenAPI (Swagger UI)
springdoc.swagger-ui.path=/api-docs
springdoc.api-docs.path=/v3/api-docs
